# Generated by Django 3.2.8 on 2021-10-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=200, unique=True)),
                ('user_name', models.CharField(default='', max_length=200, unique=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('date_of_birth', models.DateField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
