# Generated by Django 3.2.8 on 2021-10-19 13:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211019_1827'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='accountuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
