# Generated by Django 3.2.8 on 2021-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=200)),
                ('user_name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default='')),
            ],
        ),
    ]
