# Generated by Django 3.2.8 on 2021-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdetail_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
